Download public key(s) from the repo itself.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -15,11 +15,11 @@ sudo curl -L -o $TARGET $DL_BIN
 curl -L -o /tmp/okta-aws-login.sig $DL_BIN.sig
 
 if (type gpg) ; then
-  echo "Downloading GPG pub key ..."
-  gpg --keyserver hkp://ipv4.pool.sks-keyservers.net:80 --recv-key 0x3C35F6BBA50B5999
+  echo "Downloading GPG pub keyring ..."
+  curl -L -o /tmp/okta-aws-login-pub-keyring.gpg https://raw.githubusercontent.com/gilt/okta-aws-login/master/pubkeyring.gpg
 
   echo "Verifying signature ..."
-  gpg --verify /tmp/okta-aws-login.sig $TARGET || { echo "GPG signature check failed!"; exit 1; }
+  gpg --no-default-keyring --keyring /tmp/okta-aws-login-pub-keyring.gpg --verify /tmp/okta-aws-login.sig $TARGET || { echo "GPG signature check failed!"; exit 1; }
 else
   echo "GPG is not found on this system, continuing without signature verification, it's a good idea to install GPG and re-run the install script"
 fi
