Check for gpg2 first.
We expect gnupg2, it is often installed along side gnupg1 and called gpg2.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -14,18 +14,26 @@ sudo curl -L -o $TARGET $DL_BIN
 
 curl -L -o /tmp/okta-aws-login.sig $DL_BIN.sig
 
-if (type gpg) ; then
+if (type gpg2) ; then
+  GPG=gpg2
+elif (type gpg) ; then
+  GPG=gpg
+fi
+
+# Expects gnupg2.x
+if [ -z "$GPG" ] ; then
+  echo "GPG is not found on this system, continuing without signature verification, it's a good idea to install GPG and re-run the install script"
+else
+  echo "Using $(which $GPG)"
   echo "Downloading GPG pub keyring ..."
   curl -L -o /tmp/okta-aws-login-pub-keyring.gpg https://raw.githubusercontent.com/gilt/okta-aws-login/master/pubkeyring.gpg
 
   echo "Verifying signature ..."
-  gpg --no-default-keyring --keyring /tmp/okta-aws-login-pub-keyring.gpg --verify /tmp/okta-aws-login.sig $TARGET || {
+  $GPG --no-default-keyring --keyring /tmp/okta-aws-login-pub-keyring.gpg --verify /tmp/okta-aws-login.sig $TARGET || {
     echo "GPG signature check failed!";
     rm -f $TARGET
     exit 1;
   }
-else
-  echo "GPG is not found on this system, continuing without signature verification, it's a good idea to install GPG and re-run the install script"
 fi
 
 echo "Making downloaded binary executable ..."
